import { EItemCategory, EItemType } from '../enums/item';
import type { TItem } from '../types/item';

export const itemDetails: TItem[] = [
    {
        id: 'itm_001',
        name: 'Aketine',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Plant,
        imageUrl: '/src/assets/images/items/aketine.png',
    },
    {
        id: 'itm_002',
        name: 'Aketine Powder',
        type: EItemType.Products,
        tier: 2,
        category: EItemCategory.Powder,
        imageUrl: '/src/assets/images/items/aketine_powder.png',
    },
    {
        id: 'itm_003',
        name: 'Aketine Seed',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Plant,
        imageUrl: '/src/assets/images/items/aketine_seed.png',
    },
    {
        id: 'itm_004',
        name: 'Amber Rice Seed',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Plant,
        imageUrl: '/src/assets/images/items/amber_rice_seed.png',
    },
    {
        id: 'itm_005',
        name: 'Amethyst Bottle',
        type: EItemType.Products,
        tier: 2,
        category: EItemCategory.Bottle,
        imageUrl: '/src/assets/images/items/amethyst_bottle.png',
    },
    {
        id: 'itm_006',
        name: 'Amethyst Component',
        type: EItemType.Products,
        tier: 2,
        category: EItemCategory.Component,
        imageUrl: '/src/assets/images/items/amethyst_component.png',
    },
    {
        id: 'itm_007',
        name: 'Amethyst Fiber',
        type: EItemType.Products,
        tier: 2,
        category: EItemCategory.Refined,
        imageUrl: '/src/assets/images/items/amethyst_fiber.png',
    },
    {
        id: 'itm_008',
        name: 'Amethyst Ore',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Ore,
        imageUrl: '/src/assets/images/items/amethyst_ore.png',
    },
    {
        id: 'itm_009',
        name: 'Amethyst Part',
        type: EItemType.Products,
        tier: 2,
        category: EItemCategory.Parts,
        imageUrl: '/src/assets/images/items/amethyst_part.png',
    },
    {
        id: 'itm_010',
        name: 'Amethyst Powder',
        type: EItemType.Products,
        tier: 2,
        category: EItemCategory.Powder,
        imageUrl: '/src/assets/images/items/amethyst_powder.png',
    },
    {
        id: 'itm_011',
        name: 'Buck Capsule A',
        type: EItemType.Usables,
        tier: 4,
        category: EItemCategory.Consumable,
        imageUrl: '/src/assets/images/items/buck_capsule_a.png',
    },
    {
        id: 'itm_012',
        name: 'Buck Capsule B',
        type: EItemType.Usables,
        tier: 3,
        category: EItemCategory.Consumable,
        imageUrl: '/src/assets/images/items/buck_capsule_b.png',
    },
    {
        id: 'itm_013',
        name: 'Buck Capsule C',
        type: EItemType.Usables,
        tier: 3,
        category: EItemCategory.Consumable,
        imageUrl: '/src/assets/images/items/buck_capsule_c.png',
    },
    {
        id: 'itm_014',
        name: 'Buckflower',
        type: EItemType.Usables,
        tier: 1,
        category: EItemCategory.Consumable,
        imageUrl: '/src/assets/images/items/buckflower.png',
    },
    {
        id: 'itm_015',
        name: 'Buckflower Powder',
        type: EItemType.Usables,
        tier: 2,
        category: EItemCategory.Consumable,
        imageUrl: '/src/assets/images/items/buckflower_powder.png',
    },
    {
        id: 'itm_016',
        name: 'Buckflower Seed',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Plant,
        imageUrl: '/src/assets/images/items/buckflower_seed.png',
    },
    {
        id: 'itm_017',
        name: 'Bumper Rich',
        type: EItemType.Products,
        tier: 4,
        category: EItemCategory.Consumable,
        imageUrl: '/src/assets/images/items/bumper_rich.png',
    },
    {
        id: 'itm_018',
        name: 'Canned Citrome A',
        type: EItemType.Usables,
        tier: 4,
        category: EItemCategory.Consumable,
        imageUrl: '/src/assets/images/items/canned_citrome_a.png',
    },
    {
        id: 'itm_019',
        name: 'Canned Citrome B',
        type: EItemType.Usables,
        tier: 3,
        category: EItemCategory.Consumable,
        imageUrl: '/src/assets/images/items/canned_citrome_b.png',
    },
    {
        id: 'itm_020',
        name: 'Canned Citrome C',
        type: EItemType.Usables,
        tier: 3,
        category: EItemCategory.Consumable,
        imageUrl: '/src/assets/images/items/canned_citrome_c.png',
    },
    {
        id: 'itm_021',
        name: 'Carbon',
        type: EItemType.Products,
        tier: 2,
        category: EItemCategory.Refined,
        imageUrl: '/src/assets/images/items/carbon.png',
    },
    {
        id: 'itm_022',
        name: 'Carbon Powder',
        type: EItemType.Products,
        tier: 2,
        category: EItemCategory.Powder,
        imageUrl: '/src/assets/images/items/carbon_powder.png',
    },
    {
        id: 'itm_023',
        name: 'Citrome',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Plant,
        imageUrl: '/src/assets/images/items/citrome.png',
    },
    {
        id: 'itm_024',
        name: 'Citrome Powder',
        type: EItemType.Usables,
        tier: 2,
        category: EItemCategory.Consumable,
        imageUrl: '/src/assets/images/items/citrome_powder.png',
    },
    {
        id: 'itm_025',
        name: 'Citrome Seed',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Plant,
        imageUrl: '/src/assets/images/items/citrome_seed.png',
    },
    {
        id: 'itm_026',
        name: 'Cryston Bottle',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Bottle,
        imageUrl: '/src/assets/images/items/cryston_bottle.png',
    },
    {
        id: 'itm_027',
        name: 'Cryston Component',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Component,
        imageUrl: '/src/assets/images/items/cryston_component.png',
    },
    {
        id: 'itm_028',
        name: 'Cryston Fiber',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Refined,
        imageUrl: '/src/assets/images/items/cryston_fiber.png',
    },
    {
        id: 'itm_029',
        name: 'Cryston Part',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Parts,
        imageUrl: '/src/assets/images/items/cryston_part.png',
    },
    {
        id: 'itm_030',
        name: 'Cryston Powder',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Powder,
        imageUrl: '/src/assets/images/items/cryston_powder.png',
    },
    {
        id: 'itm_031',
        name: 'Dense Carbon Powder',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Powder,
        imageUrl: '/src/assets/images/items/dense_carbon_powder.png',
    },
    {
        id: 'itm_032',
        name: 'Dense Ferrium Powder',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Powder,
        imageUrl: '/src/assets/images/items/dense_ferrium_powder.png',
    },
    {
        id: 'itm_033',
        name: 'Dense Originium Powder',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Powder,
        imageUrl: '/src/assets/images/items/dense_originium_powder.png',
    },
    {
        id: 'itm_034',
        name: 'Dense Origocrust Powder',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Powder,
        imageUrl: '/src/assets/images/items/dense_origocrust_powder.png',
    },
    {
        id: 'itm_035',
        name: 'Ferrium',
        type: EItemType.Products,
        tier: 2,
        category: EItemCategory.Refined,
        imageUrl: '/src/assets/images/items/ferrium.png',
    },
    {
        id: 'itm_036',
        name: 'Ferrium Bottle',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Bottle,
        imageUrl: '/src/assets/images/items/ferrium_bottle.png',
    },
    {
        id: 'itm_037',
        name: 'Ferrium Component',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Component,
        imageUrl: '/src/assets/images/items/ferrium_component.png',
    },
    {
        id: 'itm_038',
        name: 'Ferrium Ore',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Ore,
        imageUrl: '/src/assets/images/items/ferrium_ore.png',
    },
    {
        id: 'itm_039',
        name: 'Ferrium Part',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Parts,
        imageUrl: '/src/assets/images/items/ferrium_part.png',
    },
    {
        id: 'itm_040',
        name: 'Ferrium Powder',
        type: EItemType.Products,
        tier: 2,
        category: EItemCategory.Powder,
        imageUrl: '/src/assets/images/items/ferrium_powder.png',
    },
    {
        id: 'itm_041',
        name: 'Ground Buckflower Powder',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Powder,
        imageUrl: '/src/assets/images/items/ground_buckflower_powder.png',
    },
    {
        id: 'itm_042',
        name: 'Ground Citrome Powder',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Powder,
        imageUrl: '/src/assets/images/items/ground_citrome_powder.png',
    },
    {
        id: 'itm_043',
        name: 'Hc Valley Battery',
        type: EItemType.Products,
        tier: 4,
        category: EItemCategory.Battery,
        imageUrl: '/src/assets/images/items/hc_valley_battery.png',
    },
    {
        id: 'itm_044',
        name: 'Industrial Exlosive',
        type: EItemType.Usables,
        tier: 3,
        category: EItemCategory.Other,
        imageUrl: '/src/assets/images/items/industrial_exlosive.png',
    },
    {
        id: 'itm_045',
        name: 'Jincao',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Plant,
        imageUrl: '/src/assets/images/items/jincao.png',
    },
    {
        id: 'itm_046',
        name: 'Jincao Drink',
        type: EItemType.Usables,
        tier: 3,
        category: EItemCategory.Consumable,
        imageUrl: '/src/assets/images/items/jincao_drink.png',
    },
    {
        id: 'itm_047',
        name: 'Jincao Powder',
        type: EItemType.Usables,
        tier: 2,
        category: EItemCategory.Consumable,
        imageUrl: '/src/assets/images/items/jincao_powder.png',
    },
    {
        id: 'itm_048',
        name: 'Jincao Seed',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Plant,
        imageUrl: '/src/assets/images/items/jincao_seed.png',
    },
    {
        id: 'itm_049',
        name: 'Jincao Solution',
        type: EItemType.Products,
        tier: 2,
        category: EItemCategory.Solution,
        imageUrl: '/src/assets/images/items/jincao_solution.png',
    },
    {
        id: 'itm_050',
        name: 'Lc Valley Battery',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Battery,
        imageUrl: '/src/assets/images/items/lc_valley_battery.png',
    },
    {
        id: 'itm_051',
        name: 'Lc Wuling Battery',
        type: EItemType.Natural,
        tier: 4,
        category: EItemCategory.Battery,
        imageUrl: '/src/assets/images/items/lc_wuling_battery.png',
    },
    {
        id: 'itm_052',
        name: 'Liquid Xiranite',
        type: EItemType.Products,
        tier: 4,
        category: EItemCategory.Solution,
        imageUrl: '/src/assets/images/items/liquid_xiranite.png',
    },
    {
        id: 'itm_053',
        name: 'Originium Ore',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Ore,
        imageUrl: '/src/assets/images/items/originium_ore.png',
    },
    {
        id: 'itm_054',
        name: 'Originium Powder',
        type: EItemType.Products,
        tier: 2,
        category: EItemCategory.Powder,
        imageUrl: '/src/assets/images/items/originium_powder.png',
    },
    {
        id: 'itm_055',
        name: 'Origocrust',
        type: EItemType.Products,
        tier: 2,
        category: EItemCategory.Refined,
        imageUrl: '/src/assets/images/items/origocrust.png',
    },
    {
        id: 'itm_056',
        name: 'Origocrust Powder',
        type: EItemType.Products,
        tier: 2,
        category: EItemCategory.Powder,
        imageUrl: '/src/assets/images/items/origocrust_powder.png',
    },
    {
        id: 'itm_057',
        name: 'Packed Origocrust',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Refined,
        imageUrl: '/src/assets/images/items/packed_origocrust.png',
    },
    {
        id: 'itm_058',
        name: 'Redjade Ginseng Seed',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Plant,
        imageUrl: '/src/assets/images/items/redjade_ginseng_seed.png',
    },
    {
        id: 'itm_059',
        name: 'Reed Rye Seed',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Plant,
        imageUrl: '/src/assets/images/items/reed_rye_seed.png',
    },
    {
        id: 'itm_060',
        name: 'Sandleaf',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Plant,
        imageUrl: '/src/assets/images/items/sandleaf.png',
    },
    {
        id: 'itm_061',
        name: 'Sandleaf Powder',
        type: EItemType.Products,
        tier: 2,
        category: EItemCategory.Powder,
        imageUrl: '/src/assets/images/items/sandleaf_powder.png',
    },
    {
        id: 'itm_062',
        name: 'Sandleaf Seed',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Plant,
        imageUrl: '/src/assets/images/items/sandleaf_seed.png',
    },
    {
        id: 'itm_063',
        name: 'Sc Valley Battery',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Battery,
        imageUrl: '/src/assets/images/items/sc_valley_battery.png',
    },
    {
        id: 'itm_064',
        name: 'Stabilized Carbon',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Refined,
        imageUrl: '/src/assets/images/items/stabilized_carbon.png',
    },
    {
        id: 'itm_065',
        name: 'Steel',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Refined,
        imageUrl: '/src/assets/images/items/steel.png',
    },
    {
        id: 'itm_066',
        name: 'Steel Bottle',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Bottle,
        imageUrl: '/src/assets/images/items/steel_bottle.png',
    },
    {
        id: 'itm_067',
        name: 'Steel Part',
        type: EItemType.Products,
        tier: 3,
        category: EItemCategory.Refined,
        imageUrl: '/src/assets/images/items/steel_part.png',
    },
    {
        id: 'itm_068',
        name: 'Tartpepper Seed',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Plant,
        imageUrl: '/src/assets/images/items/tartpepper_seed.png',
    },
    {
        id: 'itm_069',
        name: 'Xiranite',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Ore,
        imageUrl: '/src/assets/images/items/xiranite.png',
    },
    {
        id: 'itm_070',
        name: 'Xiranite Component',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Component,
        imageUrl: '/src/assets/images/items/xiranite_component.png',
    },
    {
        id: 'itm_071',
        name: 'Yazhen',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Plant,
        imageUrl: '/src/assets/images/items/yazhen.png',
    },
    {
        id: 'itm_072',
        name: 'Yazhen Powder',
        type: EItemType.Usables,
        tier: 1,
        category: EItemCategory.Consumable,
        imageUrl: '/src/assets/images/items/yazhen_powder.png',
    },
    {
        id: 'itm_073',
        name: 'Yazhen Seed',
        type: EItemType.Natural,
        tier: 1,
        category: EItemCategory.Plant,
        imageUrl: '/src/assets/images/items/yazhen_seed.png',
    },
    {
        id: 'itm_074',
        name: 'Yazhen Solution',
        type: EItemType.Products,
        tier: 2,
        category: EItemCategory.Component,
        imageUrl: '/src/assets/images/items/yazhen_solution.png',
    },
    {
        id: 'itm_075',
        name: 'Yazhen Syringe',
        type: EItemType.Usables,
        tier: 3,
        category: EItemCategory.Consumable,
        imageUrl: '/src/assets/images/items/yazhen_syringe.png',
    },
];
